### ISSUE TITLE
Support other types of SubjectAltNames

### ISSUE THREAD

**Issue by martinpitt** [sgallagher/sscg#4]
[SubjectAltName](https://tools.ietf.org/html/rfc5280) is not limited to `DNS:`, but other kinds of names, too. The most important one is probably `IP:` masks, so that you can e. g. do `IP:192.168.2.*`.

It would be nice for `--subject-alt-name` to support these. One possibility would be to imply a `DNS:` prefix if you don't specify one in the value, but keep an explicitly given prefix as-is.

**Comment by sgallagher** [comment]
Thanks, I'll get that added for 2.3.0.

**Comment by sgallagher** [comment]
Fixed in https://github.com/sgallagher/sscg/commit/e42c77012ff4abaf8a4ecb52ca67e9f2d45d60ff

**Comment by rglaserIoT** [comment]
I'm so used to CIDR notation by now that it didn't even cross my mind that it could be a netmask...
What i originally intended to do was to use a single IP (192.168.1.100) which resulted in the same error as above (with 192.168.1.100 instead of 192.168.17.*). So if i understand you correctly it has to be IP:192.168.1.100/255.255.255.255 in this case?

**Comment by sgallagher** [comment]
I believe that's correct, though I'll admit it has been years since I implemented this, so my memory could be rusty.
